theme: jekyll-theme-cayman
author:
  name: Vansh Gupta
  email: vg224@cornell.edu
title: Strategic Treatment Effects | STE
description: R package to calculate the Strategic Treatment Effects
social_links:
  twitter: VanshG_
  github:  g-vansh
  linkedin: vansh-g
plugins:
 - jekyll-seo-tag
github:
  manual_url: https://github.com/g-vansh/STE/raw/main/inst/STE_0.1.0.pdf
